name: CSO-validation
channels:
  - conda-forge
dependencies:
  - gdal
  - numpy
  - pandas
  - requests
  - xarray
  - ipykernel
  - matplotlib
  - seaborn
  - dask
  - rasterio
  - tqdm
  - pip:
    - git+https://github.com/communitysnowobs/mountainhub-api.git
    - git+https://github.com/communitysnowobs/validation.git
